
[workspace]
members = [
    "shared_contracts",
    "trade_loaders/mbank_emakler_csv",
    "reports/average_cost_basis_profit_report",
    "cli",  "stock_data/gpw", "predictions/upside",
]

resolver = "3"
