
[workspace]
members = [
    "shared_contracts",
    "trade_loaders/mbank_emakler_csv",
    "reports/average_cost_basis_profit_report",
    "cli",  "stock_data/gpw", "predictions/upside", "util",
]

resolver = "3"

[profile.release]
opt-level = 3
debug = false
panic = 'abort'
