[package]
name = "util"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
shared_contracts = { path = "../shared_contracts" }
polars = { version = "0.51", features = ["lazy", "serde", "full","dtype-struct", "temporal","csv"] }
