[package]
name = "gpw"
version = "0.1.0"
edition = "2024"

[features]
test-access = []

[dependencies]
calamine = "0.31"
thiserror = "2.0"
csv = "1.3"
shared_contracts = { path = "../../shared_contracts" }
serde = { version = "1.0", features = ["derive"] }
